routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/qwe', function () {
    return phpinfo();
});

Route::get('/starter', function () {
    return view('starter');
});

Auth::routes(['register' => false, 'reset' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    // Route::prefix('admin')->group(function () {
    Route::group(['middleware' => 'admin', 'prefix' => 'admin',], function () {
        Route::resource('konfigurasi', 'KonfigurasiController');
        Route::resource('konstrain', 'KonstrainController');
        Route::resource('user', 'UserController');
        Route::resource('siswa', 'SiswaController');
        Route::resource('guru', 'GuruController');
        Route::post('guru/{id}/aktifkan', 'GuruController@aktifkan')->name('guru.aktifkan');
        Route::post('siswa/{id}/aktifkan', 'SiswaController@aktifkan')->name('siswa.aktifkan');
        Route::post('mata-pelajaran/{id}/aktifkan', 'MataPelajaranController@aktifkan')->name('mata-pelajaran.aktifkan');
        Route::post('kelas/{id}/aktifkan', 'KelasController@aktifkan')->name('kelas.aktifkan');
        Route::resource('wali-kelas', 'WaliKelasController');
        Route::resource('mata-pelajaran', 'MataPelajaranController');
        Route::resource('kelas', 'KelasController');
        Route::resource('penempatan', 'PenempatanKelasController');
        Route::resource('semester', 'SemesterController');
        Route::resource('asrama', 'AsramaController');
        Route::resource('jadwal-pelajaran', 'JadwalPelajaranController');
        // Route::get('penjadwalan', 'PenjadwalanController@index')->name('penjadwalan.index');
        Route::get('penjadwalan/tabel', 'PenjadwalanController@showList')->name('penjadwalan.kelas');
        // Route::post('penjadwalan', 'PenjadwalanController@store')->name('penjadwalan.store');
        Route::resource('penjadwalan', 'PenjadwalanController');
        // Route::resource('penilaian', 'NilaiSiswaController');
    });
    // Route::group(['middleware' => ['guru','admin']], function () {
        Route::get('presensi', 'PresensiController@index')->name('presensi.index');
        Route::get('presensi/detail', 'PresensiController@list_presensi_siswa')->name('presensi.detail');
        Route::get('get-siswa', 'PresensiController@create')->name('presensi.get-siswa');
        Route::post('presensi', 'PresensiController@store')->name('presensi.store');
        Route::get('presensi/list', 'PresensiController@showList')->name('presensi.list');
        Route::get('presensi/list/{id}', 'PresensiController@show')->name('presensi.show');
        Route::get('presensi/susulan', 'PresensiController@susulan')->name('presensi.susulan');
        Route::post('presensi/susulan/simpan', 'PresensiController@simpan_susulan')->name('presensi.simpan-susulan');

        Route::get('penilaian', 'NilaiSiswaController@index')->name('penilaian.index');
        Route::get('get-list-siswa', 'NilaiSiswaController@create')->name('penilaian.get-siswa');
        Route::post('penilaian', 'NilaiSiswaController@store')->name('penilaian.store');
        Route::post('penilaian/update', 'NilaiSiswaController@update_nilai')->name('penilaian.update_nilai');
    // });
    Route::get('report', 'RaporController@report_nilai')->name('report-nilai');
    Route::get('rapor', 'RaporController@index')->name('rapor');
    Route::get('rapor/{id}/detail', 'RaporController@show')->name('rapor.detail');
    Route::get('rapor/{id}/cetak', 'RaporController@cetak')->name('rapor.cetak');
    Route::get('laporan/presensi', 'LaporanController@presensi')->name('laporan.presensi');
    Route::get('laporan/nilai', 'LaporanController@raport')->name('laporan.raport');

    Route::prefix('guru')->group(function () {
        Route::resource('jadwal', 'JadwalPelajaranController');
    });
    Route::prefix('siswa')->group(function () {
        Route::resource('jadwal', 'JadwalPelajaranController');
    });
});

resources/views/data-master/alert.blade.php
@if(session('status'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ session('status') }}
    </div>
@endif
@if(session('error'))
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ session('error') }}
    </div>
@endif
@if ($errors->any())
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <ul class="mb-0 pl-3">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/data-master/asrama.blade.php
@extends('layouts.admin', ['halaman' => 'Data Asrama'])
@push('css')
<link rel="stylesheet" href="{{ asset('plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
@endpush
@push('js')
<!-- DataTables -->
<script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script>
    $(function () {
        $("#example1").DataTable({

        });
        $('#example2').DataTable({
            "paging": false,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": false,
            // "autoWidth": false,
            // "responsive": true,
        });
    });
    $(".alert").alert();
</script>
@endpush
@section('content')
<div class="row">
    <div class="col-lg-12">
        @include('data-master.alert')
        <div class="row">

        <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <button type="button" class="btn btn-primary float-lg-left" data-toggle="modal" data-target="#modalTambah">
                    Tambah Asrama
                </button>
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr class="text-center">
                            <th>No.</th>
                            <th>Nama Asrama</th>
                            <th>Status</th>
                            <th>Created At</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($asrama as $item)
                        <tr class="text-center">
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $item->nama_asrama }}</td>
                            <td class="text-center"><h5><span class="badge {{ $item->status_asrama == 'Aktif' ? 'badge-success' : 'badge-danger' }}">{{ $item->status_asrama }}</span></h5></td>
                            <td>{{ $item->created_at }}</td>
                            <td>
                                <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#modalEdit-{{ $item->id }}" data-id="{{ $item->id }}"><i class="fas fa-edit"></i> Edit</button>
                                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modalHapus-{{ $item->id }}" data-id="{{ $item->id }}"><i class="fas fa-trash"></i> Nonaktif</button>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        </div>
        </div>
    </div>
</div>
<!-- /.row -->

<!-- Modal -->
<div class="modal fade" id="modalTambah" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <form action="{{ route('asrama.store') }}" method="POST">
            @csrf
            <div class="modal-header">
                <h5 class="modal-title">Form Tambah Asrama</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label>Nama Asrama</label>
                    <input type="text" name="nama_asrama" class="form-control" />
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                <button type="submit" value="true" class="btn btn-primary">Simpan</button>
            </div>
            </form>
        </div>
    </div>
</div>
@foreach ($asrama as $item)
<div class="modal fade" id="modalEdit-{{ $item->id }}" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <form action="{{ route('asrama.update', $item) }}" method="POST">
            @csrf
            @method('PUT')
            <div class="modal-header">
                <h5 class="modal-title">Form Ubah Asrama</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label>Nama Asrama</label>
                    <input type="text" name="nama_asrama" value="{{ $item->nama_asrama }}" class="form-control" />
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                <button type="submit" value="true" class="btn btn-primary">Simpan</button>
            </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade" id="modalHapus-{{ $item->id }}" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <form action="{{ route('asrama.destroy', $item) }}" method="POST">
            @csrf
            @method('DELETE')
            <div class="modal-header">
                <h5 class="modal-title">Hapus Data</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <div class="modal-body">
                <p class="mb-0">Apakah mau menonaktifkan asrama <strong>{{ $item->nama_asrama }}</strong>?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
                <button type="submit" class="btn btn-primary">Ya</button>
            </div>
            </form>
        </div>
    </div>
</div>
@endforeach

@endsection

resources/views/data-master/guru.blade.php
@extends('layouts.admin', ['halaman' => 'Data Guru'])
@push('css')
<link rel="stylesheet" href="{{ asset('plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
@endpush
@push('js')
<!-- DataTables -->
<script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script>
    $('.select2').select2();
    $("#example1").DataTable();
    $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
    });
    $('.checkbox-user').change(function(){
        var value = $(this).is(':checked');
        if(value){
            $('.user-create-box').show();
        }else{
            $('.user-create-box').hide();
        }
    });
    $('.checkbox-user-edit').change(function(){
        var value = $(this).is(':checked');
        if(value){
            $('.user-edit-box').show();
        }else{
            $('.user-edit-box').hide();
        }
    });
</script>
@endpush
@section('content')
<div class="row">
    <div class="col-lg-12">
        @include('data-master.alert')
        <div class="card">
            <div class="card-body">
                <button type="button" class="btn btn-primary float-lg-left" data-toggle="modal" data-target="#modalTambah">
                    Tambah Data
                </button>
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr class="text-center">
                            <th>No.</th>
                            <th>NIP</th>
                            <th>Nama Guru</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($guru as $item)
                        <tr>
                            <td class="text-center">{{ $loop->iteration }}</td>
                            <td class="text-center">{{ $item->nip }}</td>
                            <td>{{ $item->nama_guru }}</td>
                            <td class="text-center"><h5><span class="badge {{ $item->status_guru == 'Aktif' ? 'badge-success' : 'badge-danger' }}">{{ $item->status_guru }}</span></h5></td>
                            {{-- <td class="text-center">{{ isset($item->kompetensi) ? $item->kompetensi->matpel_guru->nama_matpel : 'belum ada' }}</td> --}}
                            <td class="text-center">
                                <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#modalEdit-{{ $item->id }}" data-id="{{ $item->id }}"><i class="fas fa-edit"></i> Edit</button>
                                @if ($item->status_guru == 'Aktif')
                                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modalHapus-{{ $item->id }}" data-id="{{ $item->id }}"><i class="fas fa-trash"></i> Nonaktif</button>
                                @else
                                <button type="button" class="btn btn-success" data-toggle="modal" data-target="#modalAktif-{{ $item->id }}" data-id="{{ $item->id }}"><i class="fas fa-check"></i> Aktifkan</button>
                                @endif
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- /.row -->
<!-- Modal -->
<div class="modal fade" id="modalTambah" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="{{ route('guru.store') }}" method="POST">
            @csrf
            <div class="modal-header">
                <h5 class="modal-title">Form Tambah Data Guru</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label>NIP</label>
                    <input type="text" name="nip" class="form-control" required />
                </div>
                <div class="form-group">
                    <label>Nama Guru</label>
                    <input type="text" name="nama_guru" class="form-control" required />
                </div>
                {{-- <div class="form-group">
                    <label>Mata Pelajaran Diampu</label>
                    <select name="matpel" class="form-control select2" style="width: 100%">
                        @foreach ($matpel as $item)
                        <option value="{{ $item->id }}">{{ $item->nama_matpel }}</option>
                        @endforeach
                    </select>
                </div> --}}
                {{-- <div class="form-group">
                    <input type="checkbox" name="user_create" class="checkbox-user" value="true" /> Buat user untuk login
                </div> --}}
                <div class="user-create-box">
                    <div class="form-group">
                        <label>Email</label>
                        <input type="email" name="username" class="form-control" required />
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" name="password" class="form-control" required />
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                <button type="submit" class="btn btn-primary">Simpan</button>
            </div>
            </form>
        </div>
    </div>
</div>
@foreach ($guru as $item)
<div class="modal fade" id="modalEdit-{{ $item->id }}" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="{{ route('guru.update', $item) }}" method="POST">
            @csrf
            @method('PUT')
            <div class="modal-header">
                <h5 class="modal-title">Form Ubah Data Guru</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label>NIP</label>
                    <input type="text" name="nip" value="{{ $item->nip }}" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Nama Guru</label>
                    <input type="text" name="nama_guru" value="{{ $item->nama_guru }}" class="form-control" />
                </div>
                {{-- <div class="form-group">
                    <label>Mata Pelajaran Diampu</label>
                    <select name="matpel" class="form-control select2" style="width: 100%">
                        @foreach ($matpel as $item)
                        <option value="{{ $item->id }}">{{ $item->nama_matpel }}</option>
                        @endforeach
                    </select>
                </div> --}}
                @if($item->data_user != null)
                <div class="form-group">
                    <input type="checkbox" name="user_edit" class="checkbox-user-edit" value="true" /> Edit user login
                </div>
                <div class="user-edit-box" style="display: none">
                    <div class="form-group">
                        <label>Username</label>
                        <input type="text" name="username" class="form-control" readonly value="{{ $item->data_user->email }}" />
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" name="password" class="form-control" placeholder="Isi untuk mengubah password"  />
                    </div>
                </div>
                @else
                {{-- <div class="form-group">
                    <input type="checkbox" name="user_create" class="checkbox-user" value="true" /> Buat user untuk login
                </div> --}}
                <div class="user-create-box">
                    <div class="form-group">
                        <label>Username</label>
                        <input type="text" name="username" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" name="password" class="form-control" />
                    </div>
                </div>
                @endif
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                <button type="submit" class="btn btn-primary">Simpan</button>
            </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade" id="modalHapus-{{ $item->id }}" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <form action="{{ route('guru.destroy', $item) }}" method="POST">
            @csrf
            @method('DELETE')
            <div class="modal-header">
                <h5 class="modal-title">Nonaktifkan Data Guru</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <div class="modal-body">
                <p class="mb-0">Apakah mau menonaktifkan data guru <strong>{{ $item->nama_guru }}</strong>?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
                <button type="submit" class="btn btn-primary">Ya</button>
            </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade" id="modalAktif-{{ $item->id }}" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <form action="{{ route('guru.aktifkan', $item) }}" method="POST">
            @csrf
            <div class="modal-header">
                <h5 class="modal-title">Aktifkan Data Guru</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <div class="modal-body">
                <p class="mb-0">Apakah mau mengaktifkan data guru <strong>{{ $item->nama_guru }}</strong>?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
                <button type="submit" class="btn btn-primary">Ya</button>
            </div>
            </form>
        </div>
    </div>
</div>
@endforeach
@endsection

resources/views/data-master/jadwal-tabel.blade.php
<table class="table">
    <tr>
        <th>No.</th>
        <th>Jam Pelajaran</th>
        <th>Mata Pelajaran</th>
        <th>Guru</th>
        <th></th>
    </tr>
    @foreach ($jadwal_kelas as $item)
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{ $item->jam_matpel }}</td>
            <td>{{ $item->data_matpel->nama_matpel }}</td>
            <td>{{ $item->data_guru->nama_guru }}</td>
            <td>
                <button class="btn btn-warning" data-toggle="modal" data-target="#modalUpdate-{{ $item->id }}"> Edit</button>
                <button class="btn btn-danger" data-toggle="modal" data-target="#modalHapus-{{ $item->id }}"> Hapus</button>
            </td>
        </tr>
    @endforeach
</table>
@foreach ($jadwal_kelas as $jdw)
<div class="modal fade" id="modalUpdate-{{ $jdw->id }}" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="{{ route('penjadwalan.update', $jdw->id) }}" method="POST">
            @csrf
            @method('PUT')
            <div class="modal-header">
                <h5 class="modal-title">Update Data</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label>Kelas</label>
                    <select name="kelas" class="form-control select2" style="width: 100%" required>
                        <option value="" selected disabled>-- Pilih Kelas --</option>
                        @foreach ($kelas as $item)
                        <option {{ $item->id == $jdw->kelas_id ? 'selected' : '' }} value="{{ $item->id }}">{{ $item->nama_kelas }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label>Hari</label>
                    <select name="hari" class="form-control select2" style="width: 100%" required>
                        <option value="" selected disabled>-- Pilih Hari --</option>
                        @foreach ($harian as $item)
                        <option {{ $item->hari == $jdw->hari ? 'selected' : '' }} value="{{ $item->hari }}">{{ $item->hari }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label>Jam ke</label>
                    <select name="jam" class="form-control select2" style="width: 100%" required>
                        <option value="" selected disabled>-- Pilih Jam --</option>
                        @foreach (range(1, 10) as $item)
                        <option {{ $item == $jdw->jam_matpel ? 'selected' : '' }} value="{{ $item }}">{{ $item }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label>Mata Pelajaran</label>
                    <select name="matpel" class="form-control select2" style="width: 100%" required>
                        <option value="" selected disabled>-- Pilih Matpel --</option>
                        @foreach ($matpel as $item)
                        <option {{ $item->id == $jdw->matpel_id ? 'selected' : '' }} value="{{ $item->id }}">{{ $item->nama_matpel }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label>Guru</label>
                    <select name="guru" class="form-control select2" style="width: 100%" required>
                        <option value="" selected disabled>-- Pilih Guru --</option>
                        @foreach ($guru as $item)
                        <option {{ $item->id == $jdw->guru_id ? 'selected' : '' }} value="{{ $item->id }}">{{ $item->nama_guru }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                <button type="submit" class="btn btn-primary">Simpan</button>
            </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade" id="modalHapus-{{ $jdw->id }}" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="{{ route('penjadwalan.destroy', $jdw->id) }}" method="POST">
            @csrf
            @method('DELETE')
            <div class="modal-header">
                <h5 class="modal-title">Update Data</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <div class="modal-body">
                Apakah mau menghapus jadwal ini?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                <button type="submit" class="btn btn-primary">Simpan</button>
            </div>
            </form>
        </div>
    </div>
</div>
@endforeach